added provider for Azure storage blobs
EasyMicroservices/FileManager pull request #15
Opened 2023-01-01 13:07 UTC by sabababaei

2023-01-01 16:29 UTC, Ali-YousefiTelori requested changes
Hi @sabababaei please fallow the structure.

2023-01-01 16:29 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.FileManager.AzureStorageBlobs/Interfaces/IAzureStorageBlobs.cs
> +public interface IAzureStorageBlobs
We don't need to implement new interface structure, we need to use core interface.

2023-01-01 16:29 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.FileManager.AzureStorageBlobs/Models/BlobDetail.cs
> +public class BlobDetail
We need to use core file and folder models.

2023-01-01 16:29 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.FileManager.AzureStorageBlobs/Providers/AzureStorageBlobsProvider.cs
> +public class AzureStorageBlobsProvider :IAzureStorageBlobs
It has to implement core interface.

2023-01-01 20:56 UTC, sabababaei commented on src/CSharp/EasyMicroservices.FileManager.AzureStorageBlobs/Providers/AzureStorageBlobsProvider.cs
> +public class AzureStorageBlobsProvider :IAzureStorageBlobs
I did it . Please check it out. Thanks.

2023-01-02 06:03 UTC, Ali-YousefiTelori approved these changes
@sabababaei Thanks for your contributions.

2023-01-02 06:24 UTC, Mohsen-Yaghoubi approved these changes

2023-01-02 06:25 UTC, mahdidelzendeh72 requested changes
Please Add test for Your new provider

2023-01-02 06:25 UTC, mahdidelzendeh72 commented on src/CSharp/EasyMicroservices.FileManager.AzureStorageBlobs.Tests/Providers/AzureStorageBlobsTest.cs
> +
add test for AzureBlobTest

2023-01-02 06:32 UTC, mahdidelzendeh72 approved these changes
Thank @sabababaei 
please add test also as son as possible

2023-01-02 06:34 UTC, sabababaei commented
Ok Sure!

2023-01-02 06:50 UTC, Ali-YousefiTelori commented
@sabababaei We have some conflicts in EasyMicroservices.FileManager.sln. please fix this when you want to push

2023-01-04 23:37 UTC, sabababaei commented
#12

2023-01-05 06:00 UTC, mahdidelzendeh72 approved these changes
thanks @sabababaei

2023-01-05 06:02 UTC, merged

2023-01-05 07:25 UTC, Ali-YousefiTelori reviewed
Good job

2023-01-06 03:54 UTC, AshkanAbd commented
@Ali-YousefiTelori @mahdidelzendeh72 
We have a big conflict in this PR. Golang codes and github workflows and actions has been deleted, please fix it.