issue: #8
EasyMicroservices/FileManager pull request #9
Opened 2022-12-29 18:31 UTC by Mohsen-Yaghoubi

2022-12-30 06:38 UTC, Ali-YousefiTelori requested changes
@Mohsen-Yaghoubi Thanks for your request, please check the changes.

2022-12-30 06:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservice.FileManager.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "src", "src", "{1275E0F1-4EA5-4BC0-AE72-E03D4440675E}"
Please do not change the solution architecture, it's ok, we use different folder structures in projects.

2022-12-30 06:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservice.FileManager.Tests/Providers/FileProviders/BaseFileProviderTest.cs
> +using EasyMicroservice.FileManager.Interfaces;
We have to change 'EasyMicroservice' to 'EasyMicroservices'

2022-12-30 06:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservice.FileManager.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "EasyMicroservice.FileManager.Tests", "EasyMicroservice.FileManager.Tests\EasyMicroservice.FileManager.Tests.csproj", "{A6241393-3744-4DB8-BDD8-F61
We need to change 'EasyMicroservice' folders and namespaces to 'EasyMicroservices'

2022-12-30 06:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservice.FileManager/Extensions/DirectoryExtensions.cs
> +namespace EasyMicroservice.FileManager.Extensions
For the 'Extensions' We don't use the 'extensions' namespace because of developer usage will be harder.

2022-12-30 06:38 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservice.FileManager/Extensions/FileExtensions.cs
> +namespace EasyMicroservice.FileManager.Extensions
For the 'Extensions' We don't use the 'extensions' namespace because of developer usage will be harder.

2022-12-30 15:27 UTC, Ali-YousefiTelori approved these changes
@Mohsen-Yaghoubi Thanks for your contributions.

2022-12-31 11:58 UTC, mahdidelzendeh72 approved these changes

2022-12-31 11:59 UTC, merged